name: "InferSharp-Release"

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: sudo apt-get update -y
  displayName: 'Initialize'

- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: '5.x'

- task: Bash@3
  displayName: "Build Infersharp.sln"
  inputs:
    targetType: 'inline'
    script: 'dotnet build --configuration Release Infersharp.sln'

- task: Bash@3
  displayName: "Build C# Models"
  inputs:
    targetType: 'inline'
    script: './build_csharp_models.sh'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir infersharp-release
      
      cp -r Examples infersharp-release/Examples
      
      cp run_infersharp.sh infersharp-release/
      
      cd infersharp-release
      
      mkdir Cilsil
      
      cd ..
      
      cp Cilsil/bin/Release/net5.0/*.dll infersharp-release/Cilsil/


- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'InferSharp ESRP CodeSigning'
    FolderPath: 'infersharp-release/'
    Pattern: '*.dll,*.exe'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetSign",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
        },
        {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetVerify",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

