name: "InferSharp-Release"

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: sudo apt-get update -y
  displayName: 'Initialize'

- script: ls
  displayName: 'Show files (TMP)'

- script: pwd
  displayName: 'Show current dir (TMP)'

- task: Docker@2
  displayName: 'Build and test'
  inputs:
    command: build

- script: ls
  displayName: 'Show files (TMP)'

- script: pwd
  displayName: 'Show current dir (TMP)'

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'InferSharp ESRP CodeSigning'
    FolderPath: 'infersharp/Cilsil/'
    Pattern: '*.dll,*.exe'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetSign",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
        },
        {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetVerify",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

