name: "InferSharp-AzurePipelinesExample"

pool:
  vmImage: 'ubuntu-20.04'
container:
  image: mcr.microsoft.com/infersharp:v1.2

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: Examples/Examples.sln

- script: |
    curl -o run_infersharp.sh https://raw.githubusercontent.com/microsoft/infersharp/v1.2/run_infersharp_ci.sh
    chmod +x run_infersharp.sh
    ./run_infersharp.sh $(Build.SourcesDirectory)/Examples/Examples/bin/Debug
  displayName: 'Run Infer# analysis'

- script: cat $(Build.SourcesDirectory)/infer-out/report.txt
  displayName: 'Infer# analysis result'