name: "InferSharp-AzurePipelinesExample"

pool:
  vmImage: 'ubuntu-20.04'
container:
  image: mcr.microsoft.com/infersharp:latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: Examples/Examples.sln

- script: |
    curl -o run_infersharp.sh https://raw.githubusercontent.com/microsoft/infersharp/main/run_infersharp.sh
    chmod +x run_infersharp.sh
    sh run_infersharp.sh $(Build.SourcesDirectory)/Examples/Examples/bin/Debug output
  displayName: 'Run Infer# analysis'

- script: cat $(Build.SourcesDirectory)/infer-out/filtered_bugs.txt
  displayName: 'Infer# analysis result'