name: "InferSharp-Release"

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: sudo apt-get update -y
  displayName: 'Initialize'

- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: '5.x'

- task: Bash@3
  displayName: "Build C# Models"
  inputs:
    targetType: 'inline'
    script: './build_csharp_models.sh'


- task: Bash@3
  displayName: "Build Infersharp Release"
  inputs:
    targetType: 'inline'
    script: |
      dotnet publish -c Release Cilsil/Cilsil.csproj -r ubuntu.16.10-x64

      dotnet build Examples/Examples/Examples.csproj

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir infersharp-release
      
      cp -r Examples/Examples/bin/Debug/net5.0/ infersharp-release/Examples
      
      cp run_infersharp.sh infersharp-release/
      
      cd infersharp-release
      
      mkdir Cilsil
      
      cd ..
      
      cp -r Cilsil/bin/Release/net5.0/ubuntu.16.10-x64/publish/ infersharp-release/Cilsil/

      cp .build/NOTICE.txt infersharp-release/

      cp LICENSE infersharp-release/

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'InferSharp ESRP CodeSigning'
    FolderPath: 'infersharp-release/'
    Pattern: 'Cilsil.dll'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
            "KeyCode": "CP-230072",
            "OperationSetCode": "Authenticode_SignTool6.3.9304_NPH_FDSHA256",
            "parameters": [
              {
                "parameterName": "OpusName",
                "parameterValue": "Microsoft"
              },
              {
                "parameterName": "OpusInfo",
                "parameterValue": "http://www.microsoft.com"
              },
              {
                "parameterName": "PageHash",
                "parameterValue": "/NPH"
              },​
              {
                "parameterName": "FileDigest",
                "parameterValue": "/fd sha256"
              },
              {
                "parameterName": "TimeStamp",
                "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
              }
            ],
            "ToolName": "signtool.exe",
            "ToolVersion": "6.2.9304.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'



- task: EsrpCodeSigning@1
  enabled: false
  inputs:
    ConnectedServiceName: 'InferSharp ESRP CodeSigning'
    FolderPath: 'infersharp-release/'
    Pattern: 'Cilsil.dll'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetSign",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
        },
        {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetVerify",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'infersharp-release'
    ArtifactName: 'drop'
    publishLocation: 'Container'

