name: "InferSharp-Release"

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: sudo apt-get update -y
  displayName: 'Initialize'

- task: Docker@2
  displayName: 'Build and test'
  inputs:
    command: build

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'InferSharp ESRP CodeSigning'
    FolderPath: 'Cilsil\'
    Pattern: '*.dll,*.exe'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      ​​​​​​​​​"SigningInfo" : {
        "Operations" : [
          {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetSign",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
          },
          {
          "KeyCode" : "CP-401405",
          "OperationCode" : "NuGetVerify",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
          }
        ]
      }
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
    batchSignPolicyFile: 

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

