name: "InferSharp-Release"

pool:
  vmImage: 'ubuntu-20.04'

steps:
- script: sudo apt-get update -y
  displayName: 'Initialize'

- task: Docker@2
  displayName: 'Build and test'
  inputs:
    command: build
    repository: temp/infersharp
    tags: 'latest'

- bash: docker run -v $(Build.ArtifactStagingDirectory)/release:/release --rm temp/infersharp /bin/bash -c "cd ..; tar -czvf infersharp-linux64-version.tar.gz /infersharp; cp infersharp-linux64-version.tar.gz /release/infersharp-linux64-version.tar.gz"
  displayName: Create release binaries and mount volume

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.ArtifactStagingDirectory)/release/'
    contents: 'infersharp-linux64-version.tar.gz' 
    targetFolder: '$(Build.ArtifactStagingDirectory)/infer-release/'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/infer-release/infersharp-linux64-version.tar.gz' 
    destinationFolder: '$(Build.ArtifactStagingDirectory)/infer-release/'

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'InferSharp ESRP CodeSigning'
    FolderPath: '$(Build.ArtifactStagingDirectory)/infer-release/'
    Pattern: '*.dll,*.exe'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd sha256"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '(Build.ArtifactStagingDirectory)/infer-release/infersharp' 
    includeRootFolder: true 
    archiveType: 'tar'
    tarCompression: 'gz'
    archiveFile: '$(Build.ArtifactStagingDirectory)/infer-release/infersharp-linux64-version.tar.gz' 
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/infer-release/infersharp-linux64-version.tar.gz'
    ArtifactName: 'release'
    publishLocation: 'Container'

